#!/bin/awk
BEGIN{
print "Record Book (press any key to continue)"
}
{
	print "enter values :"
 	for( i = 1 ; i < 5 ; i++)
        {
		print "Enter name :"
                getline name[i] < "-"
                print "Enter marks (out of 750) :"
                getline marks[i] < "-"
                print "Record Entered !"
        }
	for( i = 1 ; i < 5 ; i++)
	{
		percentage[i]=marks[i]*100/750
	}
	print "The records entered are"
	print "Name\tMarks\tPercentage"
	for( i = 1 ; i < 5 ; i++)
	{
		print name[i]"\t"marks[i]"\t"percentage[i]
	}
	print "The students having distinction are : "
	for( i = 1 ; i < 5 ; i++)
	{
		if ( percentage[i] > 66 ) {
		print name[i]"\t"marks[i]"\t"percentage[i] }
	}
}
END{
print "That's all folks!"
}
